### ISSUE TITLE
Add in explicit references to creds in ocelot.yml

### ISSUE THREAD

**Issue by tjtelan** [orbitalci/orbital#192]
Right now, we operate on an underdocumented secret (creds) injection functionality.

This is generally going to be ok if we improve the documentation, and do better to set user expectations.

However, if you need several secrets made available (like, if you need docker, maven, npm, and kubernetes creds), how is a user meant to achieve that? You just need to know how they move from registered creds to being injected into the buildspace. This is a lot of implicit behavior.

My biggest gripe is that the process doesn't document well enough for an ocelot.yml to be copied from a project in one (account, repo) to serve as the base of another (account, repo).

I think secrets can take more of an implementation style from kubernetes secrets.
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets

Particularly, by specifying the secret name, and at least specifying where/how the secret is mounted. Any feedback about how to approach this is welcome, as I haven't quite thought it through.

**Comment by shankj3** [comment]
Seems like it would make the ocelot.yml very large

**Comment by tjtelan** [comment]
Yup, but the ocelot.yml would fully describe secrets being used in a codified way.

In my opinion, this certainly offers a bit more hints to the user about what their build requires as inputs and supports the pipeline's overall representation in code. It would be in-line with how Shippable/TravisCI/CircleCI implement using secrets, with the expectation that secrets be provisioned prior to builds succeeding. (And gives some foundation for how we might add user accounts in the future so secret exposure may be limited to those who need it)

I'm mixed about keeping the implicit behavior at the moment (since it mostly does "just work"), but additionally including explicit secret references would only make this easier for a new user to understand.

**Comment by shankj3** [comment]
Idk, ocelot was made because build files get large and unwieldy easily, what exactly do you see this looking like

**Comment by tjtelan** [comment]
Developers who are new to Ocelot, or developers inheriting new projects don't have a story for how to manage or audit credentials for their build jobs. It's all buried in the [wiki-documented](https://github.com/level11consulting/ocelot/wiki/client#credentials), but kind of magical with the auto-injection/login/mount behavior. It's an all-or-nothing feature.

The ocelot.yml could (and probably should) help reinforce the words ocelot uses (creds as opposed to secrets -- even though I'm using them interchangibly), and help build confidence in making changes. Additionally, it will build a bridge to functionality that seems to be completely cli-driven only.

---
Perhaps when we add creds, there can be an additional option to turn off the implicit behavior?

Example: Add ssh keys to the level11consulting account that isn't auto-injected
`$ ocelot creds ssh add --identifier level11consulting-deploy --acctname level11consulting --sshfile-loc /home/leveler/.ssh/id_rsa --no-auto`

This could reduce the level of unnecessary/accidental secrets injection (remembering that this not inherently more secure, just more declarative), and reduce the potential of unrelated integrations interfering with builds.

---
Lastly, what do I see this looking like? I don't think it has to end up adding a lot of bulk.

I think there are 2 useful representations :

Reference secrets at the top:
```
image: docker
buildTool: docker
creds:
  - repo/dockerrepo1
  - k8s/cluster1
stages:
  - name: Example stage
    script:
      - docker pull <privaterepo via dockerrepo1>/imagename
      - kubectl --kubeconfig=<path via cluster1> --context=cluster1 get ns
```

Reference secrets per stage:
```
image: docker
buildTool: docker
stages:
  - name: first stage
    creds:
      - repo/dockerrepo1
    script:
      - docker pull <privaterepo via dockerrepo1>/imagename
  - name: second stage
    creds:
      - k8s/cluster1
    script:
      - kubectl --kubeconfig=<path via cluster1> --context=cluster1 get ns
```

My first thought that these representations would be functionally equivilent. The only difference being that the 2nd example runs the commands over 2 stages. Creds load during the same non-user stages stage/preflight (as opposed to the secrets-per-stage example having just-in-time behavior where secrets are loaded prior per-stage since there's unnecessary exposure to having secrets changing during builds).

Parsing the config 2nd config would identify all the creds, and load them up during setup/preflight (I forget which one).

Referencing non-existent creds would fail validation with a non-existent creds error.
